# Generated by Django 3.1.2 on 2020-10-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=98076796, unique=True),
        ),
    ]
