# Generated by Django 3.0.8 on 2020-11-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0002_auto_20201112_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=84778873, unique=True),
        ),
    ]
