# Generated by Django 3.1.2 on 2020-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0003_auto_20201105_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=93049177, unique=True),
        ),
    ]
