# Generated by Django 3.1.2 on 2020-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0003_auto_20201014_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=35128290, unique=True),
        ),
    ]
