# Generated by Django 3.1.2 on 2020-11-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0004_auto_20201105_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=53510787, unique=True),
        ),
    ]
