# Generated by Django 3.1.2 on 2020-10-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0004_auto_20201014_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=36435632, unique=True),
        ),
    ]
