# Generated by Django 3.1.2 on 2021-07-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyAndSell', '0005_auto_20210723_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=32539569, unique=True),
        ),
    ]
