# Generated by Django 3.1.2 on 2021-07-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0002_auto_20210719_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_picture',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(default='A short introduction about yourself', max_length=200),
        ),
    ]
