# Generated by Django 3.1.2 on 2020-10-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0002_auto_20201014_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, default='cover_pictures/cover.jpeg', upload_to='cover_pictures'),
        ),
    ]
